// This file was automatically generated using managers.txt and config.txt
/****************************************************************************
*
* Copyright (c) 2010 - 2014 PMC-Sierra, Inc.
*      All Rights Reserved
*
* Distribution of source code or binaries derived from this file is not
* permitted except as specifically allowed for in the PMC-Sierra
* Software License agreement.  All copies of this source code
* modified or unmodified must retain this entire copyright notice and
* comment as is.
*
* THIS SOFTWARE IS PROVIDED AS IS AND WITHOUT ANY EXPRESS OR
* IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
*
* Description: The contents of this file are auto-generated by the 
*              IPCMapGenerator it contains IPC map information.
*
* $RCSfile$
* $Revision$
* $Date$
* $Author$
* Release $Name$
*
****************************************************************************/
#ifndef IPC_MAP_H
#define IPC_MAP_H

#include <nodeid.h>
#include <ipc.h>

#ifdef __cplusplus
extern          "C" {
#endif
extern const ipc_config_t map[];

/**
 * @file
 * @brief IPC Message queue #defines.
 * 
 * The contents of this file are auto-generated by the IPCMapGenerator. It should not be modified
 * by hand.
 */

/**
 * @brief Index of the memory network inbound IPC message queue.
 */

#define IB_DATANETWORK_IDX            0


/*
 * Inbound and outbound queue indexes
 */
#define IB_PCIE_MGR2HOST_INTF0_IDX     4
#define OB_PCIE_MGR2HOST_INTF0_IDX     1
#define IB_DATA_MGR02IDMA0_IDX         1
#define OB_DATA_MGR02IDMA0_IDX         1
#define IB_DATA_MGR12IDMA0_IDX         1
#define OB_DATA_MGR12IDMA0_IDX         1
#define IB_ADMIN_MGR2IDMA0_IDX         1
#define OB_ADMIN_MGR2IDMA0_IDX         1
#define IB_ADMIN_MGR2EDMA0_IDX         0
#define OB_ADMIN_MGR2EDMA0_IDX         2
#define IB_DATA_MGR02ISECT_DMA0_IDX    3
#define OB_DATA_MGR02ISECT_DMA0_IDX    2
#define IB_DATA_MGR12ISECT_DMA0_IDX    3
#define OB_DATA_MGR12ISECT_DMA0_IDX    2
#define IB_DATA_MGR02ESECT_DMA0_IDX    2
#define OB_DATA_MGR02ESECT_DMA0_IDX    3
#define IB_DATA_MGR12ESECT_DMA0_IDX    2
#define OB_DATA_MGR12ESECT_DMA0_IDX    3
#define IB_DATA_MGR02CPLQ_MGR0_IDX     5
#define OB_DATA_MGR02CPLQ_MGR0_IDX     4
#define IB_DATA_MGR12CPLQ_MGR0_IDX     5
#define OB_DATA_MGR12CPLQ_MGR0_IDX     4
#define IB_ADMIN_MGR2CPLQ_MGR0_IDX     5
#define OB_ADMIN_MGR2CPLQ_MGR0_IDX     3
#define IB_CTRL_MGR2FLASH_INTF_LP_IDX    0
#define OB_CTRL_MGR2FLASH_INTF_LP_IDX    3
#define IB_GC_MGR02FLASH_INTF_LP_IDX    0
#define OB_GC_MGR02FLASH_INTF_LP_IDX    1
#define IB_GC_MGR12FLASH_INTF_HP_IDX    1
#define OB_GC_MGR12FLASH_INTF_HP_IDX    1
#define IB_SCHED_MGR02FLASH_INTF_LP_IDX    0
#define OB_SCHED_MGR02FLASH_INTF_LP_IDX    1
#define IB_SCHED_MGR12FLASH_INTF_HP_IDX    1
#define OB_SCHED_MGR12FLASH_INTF_HP_IDX    1
#define IB_JOURNAL_MGR2FLASH_INTF_LP_IDX    0
#define OB_JOURNAL_MGR2FLASH_INTF_LP_IDX    1
#define IB_DIAG_MGR2FLASH_INTF_LP_IDX    0
#define OB_DIAG_MGR2FLASH_INTF_LP_IDX    1
#define IB_DATA_MGR02BUFF_MGR_IDX      0
#define OB_DATA_MGR02BUFF_MGR_IDX      5
#define IB_DATA_MGR12BUFF_MGR_IDX      0
#define OB_DATA_MGR12BUFF_MGR_IDX      5
#define IB_CTRL_MGR2BUFF_MGR_IDX       0
#define OB_CTRL_MGR2BUFF_MGR_IDX       1
#define IB_GC_MGR02BUFF_MGR_IDX        0
#define OB_GC_MGR02BUFF_MGR_IDX        2
#define IB_GC_MGR12BUFF_MGR_IDX        0
#define OB_GC_MGR12BUFF_MGR_IDX        2
#define IB_LOOKUP_MGR02BUFF_MGR_IDX    0
#define OB_LOOKUP_MGR02BUFF_MGR_IDX    1
#define IB_LOOKUP_MGR12BUFF_MGR_IDX    0
#define OB_LOOKUP_MGR12BUFF_MGR_IDX    1
#define IB_FLASH_BUFM_A2BUFF_MGR_IDX    0
#define OB_FLASH_BUFM_A2BUFF_MGR_IDX    16
#define IB_FLASH_BUFM_F2BUFF_MGR_IDX    0
#define OB_FLASH_BUFM_F2BUFF_MGR_IDX    16
#define IB_JOURNAL_MGR2XOR_ENG_IDX     0
#define OB_JOURNAL_MGR2XOR_ENG_IDX     2
#define IB_LOOKUP_MGR02XOR_ENG_IDX     0
#define OB_LOOKUP_MGR02XOR_ENG_IDX     2
#define IB_LOOKUP_MGR12XOR_ENG_IDX     0
#define OB_LOOKUP_MGR12XOR_ENG_IDX     2
#define IB_SCHED_MGR02XOR_ENG_I